import { NextRequest, NextResponse } from 'next/server';
import { ZipArchive } from 'archiver';
import { createReadStream, type Stats } from 'node:fs';
import { stat, readdir } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import { Readable } from 'node:stream';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const PROJECT_ROOT = process.cwd();

// Directories & files that must NEVER be packaged into the downloadable ZIP.
const EXCLUDE_DIRS = new Set([
  'node_modules',
  '.next',
  '.git',
  '.vercel',
  '.idea',
  '.vscode',
  '.cache',
  '.turbo',
  'db',
  'download',
  'tool-results',
  'agent-ctx',
  'upload',
  'skills',
  'mini-services',
  'examples',
  '__pycache__',
  'coverage',
  '.sst',
  'dist',
  'out',
]);

const EXCLUDE_FILES = new Set([
  '.env',
  '.env.local',
  '.env.production',
  '.env.development',
  'dev.log',
  'server.log',
  'dev.out.log',
  'bun.lock',
  'bun.lockb',
  'package-lock.json',
  'yarn.lock',
  '.DS_Store',
  'worklog.md',
  '--fullpage',
  'tsconfig.tsbuildinfo',
]);

const EXCLUDE_SUFFIXES = ['.db', '.db-journal', '.log'];

interface WalkEntry {
  absPath: string;
  relPath: string;
  size: number;
  isDir: boolean;
}

/** Recursively walk the project, honouring exclude rules. */
async function walk(dir: string, base: string, out: WalkEntry[]): Promise<void> {
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    if (EXCLUDE_DIRS.has(entry) || EXCLUDE_FILES.has(entry)) continue;
    const absPath = join(dir, entry);
    let s: Stats;
    try {
      s = await stat(absPath);
    } catch {
      continue;
    }
    const relPath = relative(base, absPath).split(sep).join('/');
    if (s.isDirectory()) {
      out.push({ absPath, relPath, size: 0, isDir: true });
      await walk(absPath, base, out);
    } else if (s.isFile()) {
      if (EXCLUDE_SUFFIXES.some((sfx) => entry.toLowerCase().endsWith(sfx))) continue;
      out.push({ absPath, relPath, size: s.size, isDir: false });
    }
  }
}

/**
 * GET /api/download-source
 * Streams a ZIP archive of the entire project source code.
 */
export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const fileName =
    (url.searchParams.get('name') || 'rssb-cvs-src').replace(/[^\w.-]/g, '') ||
    'rssb-cvs-src';

  const entries: WalkEntry[] = [];
  await walk(PROJECT_ROOT, PROJECT_ROOT, entries);

  // archiver v8: use the ZipArchive class directly (pure ESM).
  const archive = new ZipArchive({
    zlib: { level: 6 },
    comment:
      'RSSB Counter Verification System — full source export. Generated by /api/download-source',
  });

  const chunks: Buffer[] = [];
  archive.on('data', (c: Buffer) => chunks.push(c));

  const done = new Promise<void>((resolve, reject) => {
    archive.on('end', resolve);
    archive.on('error', reject);
  });

  let totalFiles = 0;
  let totalBytes = 0;
  for (const e of entries) {
    if (e.isDir) continue;
    archive.append(createReadStream(e.absPath), { name: e.relPath, mode: 0o644 });
    totalFiles++;
    totalBytes += e.size;
  }

  const readme = `# RSSB Counter Verification System

This ZIP contains the complete source code for the RSSB Counter Verification
System — a Next.js 16 + Prisma + shadcn/ui web application for verifying
pharmacy voucher claims against the Rwanda Social Security Board.

## Quick start

\`\`\`bash
bun install
bun run db:push        # create the SQLite database
bun run dev            # start the dev server on http://localhost:3000
\`\`\`

## Deploy on Vercel

1. Push this folder to a GitHub repository.
2. Import the repo on https://vercel.com — the included vercel.json and
   next.config.ts configure everything automatically.
3. Set the DATABASE_URL environment variable (or switch the Prisma
   datasource to Turso / Vercel Postgres for a persistent serverless DB).
4. Deploy. The app is a PWA — install it from the browser on any device.

## Scripts

- bun run dev          — start dev server (port 3000)
- bun run build        — production build (standalone)
- bun run vercel-build — Vercel build (prisma generate + next build)
- bun run lint         — ESLint
- bun run pwa:icons    — regenerate PWA icons from public/icons/icon.svg
- bun run db:push      — push Prisma schema to the database

## PWA

The app is installable as a Progressive Web App:
- manifest:       public/manifest.json
- service worker: public/sw.js  (offline-first caching)
- icons:          public/icons/  (192, 512, maskable, apple-touch, favicon)
- metadata:       src/app/layout.tsx (theme-color, apple-web-app, OG, Twitter)

Generated: ${new Date().toISOString()}
Files: ${totalFiles}
`;
  archive.append(readme, { name: 'README-EXPORT.md' });

  await archive.finalize();
  await done;

  const zipBuffer = Buffer.concat(chunks);

  const headers = new Headers();
  headers.set('Content-Type', 'application/zip');
  headers.set('Content-Disposition', `attachment; filename="${fileName}.zip"`);
  headers.set('Content-Length', String(zipBuffer.byteLength));
  headers.set('Cache-Control', 'no-store, no-cache, must-revalidate');
  headers.set('X-Export-File-Count', String(totalFiles));
  headers.set('X-Export-Source-Bytes', String(totalBytes));

  return new NextResponse(Readable.from([zipBuffer]) as unknown as ReadableStream, {
    status: 200,
    headers,
  });
}
